apiVersion: v1
kind: Service
metadata:
    name: architeuthis-front-page
spec:
    type: LoadBalancer
    selector:
        app: architeuthis-front-page
    ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: architeuthis-front-page-pv
    labels:
        app: architeuthis-front-page-pv
spec:
    storageClassName: manual
    capacity:
        storage: 10Mi
    accessModes:
        - ReadOnlyMany
    hostPath:
        path: /var/local/architeuthis-front-page
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: architeuthis-front-page-pv-claim
    labels:
        app: architeuthis-front-page-pv
spec:
    storageClassName: manual
    accessModes:
        - ReadOnlyMany
    resources:
        requests:
            storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: architeuthis-front-page
    labels:
        app: architeuthis-front-page
spec:
    replicas: 1
    selector:
        matchLabels:
            app: architeuthis-front-page
    template:
        metadata:
            labels:
                app: architeuthis-front-page
        spec:
            imagePullSecrets:
                - name: regcred
            containers:
                - name: architeuthis-front-page
                  image: docker.fela.space/architeuthis-front-page:0
                  ports:
                      - containerPort: 8080
                  volumeMounts:
                      - name: architeuthis-front-page-pv
                        mountPath: /hostdata
                  envFrom:
                      - configMapRef:
                            name: architeuthis-front-page
                  env:
                      - name: NODE_ENV
                        value: production
                  livenessProbe:
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      httpGet:
                          path: /api/health
                          port: 8080
                  readinessProbe:
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      httpGet:
                          path: /api/health
                          port: 8080
            volumes:
                - name: architeuthis-front-page-pv
                  persistentVolumeClaim:
                      claimName: architeuthis-front-page-pv-claim
