apiVersion: v1
kind: Service
metadata:
  name: architeuthis-front-page
spec:
  type: LoadBalancer
  selector:
    app: architeuthis-front-page
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: architeuthis-front-page
  labels:
    app: architeuthis-front-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: architeuthis-front-page
  template:
    metadata:
      labels:
        app: architeuthis-front-page
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: architeuthis-front-page
          image: docker.fela.space/architeuthis-front-page:0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: architeuthis-front-page
          env:
            - name: NODE_ENV
              value: production
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
